# Generated by Django 5.0 on 2024-01-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(choices=[('default', 'Default'), ('home', 'Home'), ('work', 'work'), ('health', 'Health'), ('savings', 'Savings'), ('social', 'Social')], default='default', max_length=10),
        ),
    ]
